name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose --release
      - name: install wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: install tools (trunk)
        run: cargo install trunk 
      - name: build
        run: cd frontend && trunk build --release

    
  
